### ISSUE TITLE
Gridsearch: Summarize Gridsearch Results

### ISSUE THREAD

**Issue by jxnl** [jxnl/TwitterAlcoholDetection#21]
- [x] Data Access
- [ ] Notebook

**Comment by jxnl** [comment]
some problems have occured and we'll need to have some kind of chunking code so we can break up a model into smaller sizes

**Comment by jxnl** [comment]
most code is written. I have get to create a notebook that goes over performance

**Comment by rumichunara** [comment]
Awesome!
