### ISSUE TITLE
Ideas for user level analytics

### ISSUE THREAD

**Issue by jxnl** [jxnl/TwitterAlcoholDetection#38]
Currently I don't believe that first person levels are as accurate as I'd like them to be before doing any kind of individual level stuff.

However I've also considered looking at some of the following:
# Groupbys

Currently the groupby are tweet based. What could that look like for a user based groupby
# Double indexing

Make a time series per (by day) user and find interesting users
# Bounds of error for histograms

**Comment by jxnl** [comment]
@rumichunara  theres something intereesting.

what if we compared time series of something like San Fransisco to New York and maybe we see that new yorkers start later while SF people end earlier. (or whatever it may be)

**Comment by rumichunara** [comment]
That's very interesting. I totally agree that population-level temporal
trends are useful, whether that's people in different cities or thinking
further women vs men etc.

**Comment by jxnl** [comment]
A lot of weird results.

Gender is a bit harder to determine if I remember correctly its not something that is public.
