### ISSUE TITLE
Feature Importance

### ISSUE THREAD

**Issue by jxnl** [jxnl/TwitterAlcoholDetection#9]
A notebook should be made that can test accuracy improvement for each feature in a forward step fashion. this notebook should also describe how the features are implemented.

**Comment by jxnl** [comment]
I should make sure this writing can be used for both my work term report and the paper.

**Comment by jxnl** [comment]
Using a base LinearRegression Model this following table will describe the different AUC metrics for each features

| Feature | AUC |
| --- | --- |
| Text | .83 |
| Age | .50 |
| User | .58 |
| Time | .53 |
| All | .83 |

**Comment by jxnl** [comment]
From the above comment we see that Age might not have any relevance. and that while `User` and `Time` has information, in the presence of `Text` it dissolves away.

My idea might be to have a `Text` only predictor and then use the `clf.predict_proba` as a feature. in a way, projecting the data down. then we'll see if there is any relevance.

**Comment by jxnl** [comment]
It also seems that by including time information that is 1-hot encoded, we actually consistently drop in performance @rumichunara so more work will need to go into that.

**Comment by rumichunara** [comment]
Ok let's discuss more on Friday but agree it will be good to see how well the text only features can perform especially given the weak score on multiclass per your earlier mail.
